#!/bin/bash
set -e

# verificar dialog
if [ ! -x /usr/bin/dialog ]; then
    echo ""
    echo "El paquete dialog no esta instalado."
    echo "Por favor instalalo, se va a cancelar la instalacion."
    echo ""
    echo -n "Presiona enter para continuar"
    read -sn 1
    exit 1
# verificar solo at
elif [ ! -x /usr/bin/at ]; then
    echo ""
    echo "El paquete at no esta instalado."
    echo "Por favor instalalo, se va a cancelar la instalacion."
    echo ""
    echo -n "Presiona enter para continuar"
    read -sn 1
    exit 1
fi
