#!/bin/bash
set -e

tput smcup
clear
# crear una caja con echos y ascci drawing boxes
# el borde de color azul y el texto de color blanco
# es un selector de opciones
# la opciocion seleccionada es de color verde
# la opcion no seleccionada es de color blanco
# la opcion de salir es de color rojo
# la opcion seleccionada por defecto es la primera
# agregar un feedback que muestre que con las flechas se puede mover
# y con enter seleccionar
echo -e "\e[1;34m┌───────────────────── GLAM ─────────────────────┐"
echo -e "\e[1;34m│                                                │"
echo -e "\e[1;34m│\e[1;37mDeseas guardar los archivos de registro         \e[1;34m│"
echo -e "\e[1;34m│\e[1;37m       antes de desinstalar?                    \e[1;34m│"
echo -e "\e[1;34m│                                                │"
echo -e "\e[1;34m│\e[1;32m  1) Si                                         \e[1;34m│"
echo -e "\e[1;34m│\e[1;37m  2) No                                         \e[1;34m│"
echo -e "\e[1;34m│\e[1;31m  3) Salir                                      \e[1;34m│"
echo -e "\e[1;34m│                                                │"
echo -e "\e[1;34m│ \e[1;37m↑ ↓: Moverse \e[1;32mEnter: Seleccionar \e[1;31mEsc: Salir \e[1;34m    │"
echo -e "\e[1;34m└────────────────────────────────────────────────┘\e[0m"

# hacer el movimiento con las flechas
while true; do
    read -s -n 1 key
    if [[ $key == '\e' ]]; then
        read -s -n 2 key
        if [[ $key == '[A' ]]; then
            # mover hacia arriba
            tput cup 8 2
            echo -e "\e[1;32m  1) Si                                         \e[0m"
            tput cup 9 2
            echo -e "\e[1;37m  2) No                                         \e[0m"
        elif [[ $key == '[B' ]]; then
            # mover hacia abajo
        fi
    fi
done
